export type Difficulty = 'easy' | 'medium' | 'hard';

// eslint-disable-next-line react-refresh/only-export-components
export const CAMBRIDGE_LEVELS: Record<Difficulty, { label: string; cefr: string; exams: string }> = {
  easy: { label: 'Easy', cefr: 'A1–A2', exams: 'Starters · Movers · Flyers · A2 Key' },
  medium: { label: 'Medium', cefr: 'B1–B2', exams: 'B1 Preliminary · B2 First' },
  hard: { label: 'Hard', cefr: 'C1–C2', exams: 'C1 Advanced · C2 Proficiency' },
};

const createSentences = (subjects: string[], endings: string[], count: number) =>
  Array.from({ length: count }, (_, index) => {
    const subject = subjects[Math.floor(index / endings.length) % subjects.length];
    const ending = endings[index % endings.length];
    return `${subject} ${ending}`;
  });

const createCombinationSentences = (subjects: string[], actions: string[], details: string[]) =>
  subjects.flatMap(subject => actions.flatMap(action => details.map(detail => `${subject} ${action} ${detail}`)));

const cleanSentences = (sentences: string[]) =>
  sentences.map(sentence => sentence.replace(/[.!?]+$/, ''));

const easyGenerated = createSentences(
  [
    'I can', 'We can', 'You can', 'They can', 'My friend can',
    'A good habit can', 'Daily practice can', 'A clear goal can',
    'Small changes can', 'Quiet focus can', 'Kind words can', 'Fresh ideas can',
    'A short break can', 'Regular reading can', 'Simple plans can', 'Patient effort can',
  ],
  [
    'build confidence.', 'make work easier.', 'open new doors.', 'bring people closer.',
    'turn mistakes into lessons.', 'help us stay calm.', 'create better habits.',
    'make a real difference.', 'keep the mind active.', 'lead to good results.',
  ],
  152,
);

const mediumGenerated = createSentences(
  [
    'A thoughtful learner', 'A curious mind', 'A steady routine', 'Good preparation',
    'Patient practice', 'An honest review', 'A clear explanation', 'A useful question',
    'Careful attention', 'A positive attitude', 'A quiet workspace', 'Regular feedback',
    'A simple system', 'Consistent effort', 'An open conversation', 'A challenging goal',
  ],
  [
    'turns difficult ideas into practical skills.', 'helps us notice progress over time.',
    'makes complex tasks easier to manage.', 'creates space for better decisions.',
    'keeps important details from being forgotten.', 'gives every new attempt a purpose.',
    'helps people learn from unexpected results.', 'builds confidence through small successes.',
    'makes room for creativity and careful thought.', 'can transform a routine into meaningful progress.',
  ],
  152,
);

const hardGenerated = createSentences(
  [
    'Meaningful progress often begins when', 'The strongest ideas emerge after',
    'Long-term improvement becomes possible when', 'A thoughtful decision requires that',
    'The most reliable results appear when', 'Creative solutions are easier to find when',
    'A resilient team becomes stronger when', 'Lasting change usually depends on',
    'An ambitious goal becomes manageable once', 'Good judgment improves whenever',
    'A difficult problem deserves attention before', 'Effective communication succeeds when',
    'A careful experiment can teach us why', 'Real understanding develops as',
    'A useful lesson remains valuable even when', 'Independent thinking matters because',
  ],
  [
    'we question the assumptions behind our first answer',
    'we compare different perspectives without dismissing either one',
    'we accept uncertainty and continue testing what we believe',
    'we turn temporary setbacks into information for the next attempt',
    'we balance immediate results with consequences that may appear later',
    'we make time to examine both the evidence and the reasoning',
    'we replace vague intentions with specific actions and honest feedback',
    'we remain patient enough to recognize patterns that are not obvious at first',
    'we understand that consistency is often more powerful than intensity',
    'we listen carefully before deciding which conclusion the facts support',
  ],
  151,
);

const easyAdditional = createSentences(
  [
    'The morning sun can', 'A warm cup of tea can', 'One kind message can', 'A tidy desk can',
    'A gentle walk can', 'Fresh air can', 'A shared meal can', 'A good book can',
    'A mindful breath can', 'A useful note can', 'A simple question can', 'A friendly smile can',
    'A clean room can', 'A quiet song can', 'An early start can', 'A clear answer can',
    'A helping hand can',
  ],
  [
    'brighten the whole morning.', 'make a busy day feel lighter.', 'help us find a new idea.',
    'give us energy for the next task.', 'make a difficult moment easier.', 'bring a little peace.',
    'remind us to slow down.', 'help everyone feel welcome.', 'turn a plan into action.',
    'make learning more enjoyable.',
  ],
  167,
);

const mediumAdditional = createSentences(
  [
    'A well-organized schedule', 'A patient teacher', 'A reliable teammate', 'A careful reader',
    'A focused conversation', 'A balanced routine', 'A practical example', 'A written reminder',
    'A shared responsibility', 'A realistic deadline', 'A calm response', 'A thoughtful plan',
    'A useful comparison', 'A regular review', 'A clear priority', 'A flexible approach',
    'A welcoming environment',
  ],
  [
    'helps important work move forward without unnecessary stress.',
    'allows people to solve problems with greater confidence.',
    'makes it easier to understand how separate details connect.',
    'can improve both the quality and the speed of a decision.',
    'creates a stronger foundation for future progress.',
    'encourages everyone to contribute their best ideas.',
    'turns a confusing task into a series of manageable steps.',
    'helps us respond thoughtfully instead of reacting too quickly.',
    'can reveal opportunities that were hidden by routine assumptions.',
    'makes progress visible even when the final result is still distant.',
  ],
  167,
);

const hardAdditional = createSentences(
  [
    'A responsible leader recognizes that', 'A careful investigation reveals how',
    'A lasting solution becomes possible once', 'A complex conversation improves when',
    'A mature perspective accepts that', 'A strong argument depends on whether',
    'A sustainable process requires that', 'A difficult negotiation succeeds when',
    'A valuable discovery often occurs after', 'A fair evaluation considers whether',
    'A precise explanation matters because', 'A balanced conclusion emerges when',
    'A disciplined approach prevents us from', 'A generous interpretation allows us to',
    'A meaningful collaboration begins when', 'A careful observer notices that',
    'A trustworthy system remains useful only when',
  ],
  [
    'we distinguish what the evidence shows from what we merely expect',
    'we identify the limits of a method before applying it elsewhere',
    'we consider the long-term effects alongside the immediate benefits',
    'we make room for disagreement without turning it into personal conflict',
    'we revise our plans whenever new information changes the situation',
    'we explain not only what happened but also why it happened that way',
    'we protect essential principles while remaining open to practical change',
    'we test a promising idea against the conditions it must actually survive',
    'we acknowledge uncertainty instead of hiding it behind confident language',
    'we measure success by the value created for everyone affected by the outcome',
  ],
  166,
);

const cambridgeGenerated: Record<Difficulty, string[]> = {
  easy: createCombinationSentences(
    ['I', 'You', 'We', 'They', 'My brother', 'Her sister', 'The teacher', 'Our neighbor', 'A young student', 'The kind child'],
    ['like', 'need', 'use', 'carry', 'clean', 'open', 'read', 'watch', 'visit', 'help'],
    ['a small blue bag', 'the new classroom', 'some fresh fruit', 'an interesting book', 'the sunny garden', 'a warm cup of tea', 'our old family photo', 'the busy town center', 'a simple English story', 'the friendly dog'],
  ),
  medium: createCombinationSentences(
    ['The research team', 'A careful manager', 'The local community', 'An experienced teacher', 'Several young adults', 'The small business', 'A responsible traveler', 'The health organization', 'Our university class', 'A reliable assistant'],
    ['examined', 'developed', 'organized', 'compared', 'discussed', 'improved', 'recorded', 'prepared', 'evaluated', 'explained'],
    ['the results of the recent survey', 'a practical response to the problem', 'the possible effects on local residents', 'a detailed plan for the following year', 'the information provided by several sources', 'a more efficient way to manage resources', 'the relationship between diet and exercise', 'the main reasons behind the decision', 'a useful example for new learners', 'the long-term value of regular practice'],
  ),
  hard: createCombinationSentences(
    ['A comprehensive investigation', 'The independent committee', 'A sustainable development strategy', 'The revised academic framework', 'An experienced policy adviser', 'The international research project', 'A carefully designed experiment', 'The organization’s long-term plan', 'A nuanced interpretation of the evidence', 'The proposed institutional reform'],
    ['demonstrates', 'challenges', 'examines', 'identifies', 'questions', 'clarifies', 'anticipates', 'establishes', 'illustrates', 'reassesses'],
    ['how apparently minor decisions can produce substantial consequences over time', 'whether the available evidence is sufficient to support the proposed conclusion', 'the assumptions that have influenced the debate for several decades', 'why a flexible response is preferable to a rigid set of instructions', 'the extent to which economic growth can coexist with environmental responsibility', 'how competing priorities should be balanced during periods of uncertainty', 'the limitations of a method that appears reliable in controlled conditions', 'whether the original objectives remain relevant in the current context', 'the complex relationship between individual choices and collective outcomes', 'how a carefully reasoned alternative could address the underlying difficulty'],
  ),
};

const grammarSentences: Record<Difficulty, string[]> = {
  easy: [
    'I am ready for my English lesson',
    'She does not like noisy places',
    'Do you practice English every day',
    'We are learning new words together',
    'He went to the library yesterday',
    'They will visit their teacher tomorrow',
    'There is a notebook on the table',
    'There are three useful examples here',
    'I have already finished my homework',
    'She has lived here for two years',
    'Please listen carefully before you answer',
    'If you practice often, you will improve',
  ],
  medium: [
    'I have been studying English since the beginning of the year',
    'She was reading when her friend called',
    'They had finished dinner before the movie started',
    'If I had more time, I would read another book',
    'The lesson was easier than I expected',
    'This is the most useful exercise in the workbook',
    'He asked me whether I understood the instructions',
    'Although the weather was cold, we continued our walk',
    'The project must be completed before Friday afternoon',
    'People who read regularly often learn new words faster',
    'I am not sure which answer the teacher prefers',
    'By the time we arrived, the class had already begun',
  ],
  hard: [
    'If the researchers had checked the data earlier, they might have avoided the error',
    'The book, which was published last year, has already become a valuable reference',
    'Having completed the experiment, the students carefully compared their results',
    'The manager asked whether the revised proposal could be submitted before noon',
    'Despite being exhausted after the journey, she continued working on the report',
    'What matters most is how consistently we apply what we have learned',
    'The more carefully you listen, the easier it becomes to recognize natural phrases',
    'Unless the evidence changes, the committee is unlikely to revise its conclusion',
    'The course encourages learners to explain ideas that they would normally avoid discussing',
    'It is essential that every participant be given enough time to consider the question',
    'The teacher explained that the assignment should have been completed before the meeting',
    'Had we known about the delay, we would have chosen a different route',
  ],
};

const dailyVocabularySentences: Record<Difficulty, string[]> = {
  easy: [
    'I usually wake up at seven and make my bed',
    'Please turn off the light before you leave the room',
    'My phone is charging on the table near the window',
    'We need to buy milk bread and fresh vegetables today',
    'She keeps her keys in a small bowl by the door',
    'The bus is late so we may miss the first class',
    'I left my coat at home because the weather is warm',
    'He is washing the dishes after dinner',
    'Can you send me the address by text message',
    'The supermarket closes at nine on weekdays',
    'My sister is waiting for a package this afternoon',
    'We often cook rice and chicken for dinner',
    'I drink a glass of water when I feel thirsty',
    'The doctor told him to rest and take this medicine',
    'Please put the clean towels in the bathroom',
    'I walk to work when the traffic is busy',
    'Her alarm rang early but she went back to sleep',
    'The children are doing their homework at the kitchen table',
    'I need a quiet place to read for thirty minutes',
    'Our neighbor grows tomatoes in the garden',
    'She forgot her umbrella and got wet on the way home',
    'The coffee shop is next to the train station',
    'I check my calendar before I make a plan',
    'He bought a birthday card for his mother',
    'Please wait here while I find the right size',
    'The room feels cooler when we open the window',
    'I usually listen to music while I clean the house',
    'They invited us to dinner on Saturday evening',
    'My jacket has a broken button near the pocket',
    'We should leave now if we want to arrive on time',
  ],
  medium: [
    'I made an appointment with the dentist for next Tuesday',
    'The delivery was delayed because the address was incomplete',
    'She checked the receipt before leaving the store',
    'Our team uses a shared calendar to arrange weekly meetings',
    'He forgot to renew his train card before the journey',
    'The restaurant was crowded so we booked a table online',
    'I keep a list of errands to finish after work',
    'The landlord agreed to repair the broken heating system',
    'She compared several phone plans before choosing one',
    'We postponed the picnic because the forecast predicted heavy rain',
    'The cashier explained how to return the damaged product',
    'I have to collect a prescription from the pharmacy this evening',
    'He prepared lunch in advance to save time during the week',
    'The train platform changed while we were waiting for an announcement',
    'She usually reviews her budget before making a large purchase',
    'The meeting started late because the main speaker missed the bus',
    'Please let me know if you need help with the application form',
    'Our internet connection becomes unreliable during the evening',
    'They replaced the old furniture after moving into the apartment',
    'I forgot my password and had to reset it through the website',
    'The hotel receptionist recommended a quiet place for breakfast',
    'He apologized for the misunderstanding and offered a practical solution',
    'We shared the cost of the taxi after the concert',
    'She avoids processed food and prepares most meals at home',
    'The mechanic found a small problem with the car battery',
    'I saved the document in a folder so I could find it later',
    'The local library offers free courses for adult learners',
    'They adjusted the schedule to give everyone enough preparation time',
    'I brought a reusable bottle instead of buying another one',
    'The customer service agent answered my question clearly',
  ],
  hard: [
    'The household budget became easier to manage after we reviewed our regular expenses',
    'She negotiated a flexible working arrangement to reduce her daily commute',
    'The pharmacy provided clear instructions about the dosage and possible side effects',
    'He postponed the purchase until he had compared the long-term costs',
    'The apartment required minor renovations before it was comfortable to live in',
    'Our travel insurance covered the additional accommodation after the flight was cancelled',
    'The customer requested a refund because the replacement product was also defective',
    'She keeps digital copies of important documents in case the originals are lost',
    'The neighborhood association introduced a recycling scheme for local households',
    'He arranged a routine inspection after noticing an unusual noise from the engine',
    'The appointment was rescheduled because the specialist was unexpectedly unavailable',
    'They reduced unnecessary subscriptions after examining their monthly bank statement',
    'The retailer offered a partial refund rather than replacing the item immediately',
    'She prepared a concise explanation before discussing the complaint with the manager',
    'The public transport network is convenient, although service interruptions remain common',
    'He prioritizes essential tasks when an unexpected responsibility affects his schedule',
    'The building manager notified residents that maintenance work would begin next month',
    'We chose a slightly more expensive service because its cancellation policy was clearer',
    'The doctor recommended regular exercise while acknowledging the patient\'s limited free time',
    'The online booking system prevented us from selecting seats next to each other',
    'She kept the conversation constructive despite receiving an unfair complaint',
    'The repair was completed promptly, but the warranty did not cover the additional parts',
    'He developed a reliable routine for balancing household responsibilities and personal study',
    'The travel delay created practical difficulties for passengers with connecting flights',
    'The company updated its privacy policy after customers raised concerns about personal data',
    'A realistic schedule is more useful than an ambitious plan that cannot be maintained',
    'She clarified the payment conditions before agreeing to the service contract',
    'The community center provides accessible facilities for residents with different needs',
    'He made a deliberate effort to reduce screen time before going to bed',
    'The supplier confirmed that the replacement parts would arrive within three working days',
  ],
};

const vocabularySentences: Record<Difficulty, string[]> = {
  easy: [
    'The bright window made the small room feel welcoming',
    'Please place the empty bottle beside the kitchen sink',
    'The helpful guide showed us a quiet path through the park',
    'A healthy breakfast gives you energy for the morning',
    'The careful driver noticed a narrow bridge ahead',
    'We packed a light jacket because the evening might be cool',
    'The local market sells fresh fruit and handmade gifts',
    'Her favorite hobby is painting colorful pictures',
    'The simple recipe needs flour, eggs, and a little butter',
    'A friendly neighbor offered useful advice',
    'The train arrived at the busy station on time',
    'Reading short stories is an enjoyable way to learn',
    ...dailyVocabularySentences.easy,
  ],
  medium: [
    'The reliable equipment helped the team complete the difficult task',
    'A flexible schedule makes it easier to balance work and study',
    'The speaker gave a clear explanation of the unfamiliar process',
    'Our neighborhood has several affordable restaurants near the river',
    'The museum displays remarkable objects from ancient civilizations',
    'A thoughtful response can prevent a small disagreement from becoming serious',
    'The company introduced an efficient system for organizing customer requests',
    'Regular exercise can improve concentration as well as physical health',
    'The journalist confirmed the information with an independent source',
    'A practical solution should be affordable, reliable, and easy to maintain',
    'The students discussed the environmental impact of excessive packaging',
    'The unfamiliar vocabulary became easier after we saw it in context',
    ...dailyVocabularySentences.medium,
  ],
  hard: [
    'The architect proposed a sustainable design that would reduce the building’s energy consumption',
    'The investigation revealed several inconsistencies in the original financial report',
    'Effective collaboration depends on transparent communication and shared responsibility',
    'The speaker presented a compelling argument supported by independent evidence',
    'A sophisticated vocabulary is useful only when each word is used with precision',
    'The expedition required careful preparation because the terrain was unpredictable',
    'The policy aims to encourage innovation while protecting vulnerable communities',
    'The scientist recorded a significant increase in biodiversity after the restoration project',
    'A comprehensive review identified practical improvements to the organization’s workflow',
    'The negotiation reached a temporary agreement despite considerable disagreement',
    'The concept became more accessible after the professor provided a concrete example',
    'Long-term sustainability requires investment, patience, and responsible decision-making',
    ...dailyVocabularySentences.hard,
  ],
};

// Curated sentences add topic variety and natural language beyond the
// generated practice patterns above.
const diverseSentenceBank: Record<Difficulty, string[]> = {
  easy: [
    'The blue bus stops near my house every morning',
    'Please bring an umbrella because the sky looks dark',
    'My sister enjoys cooking simple meals for our family',
    'The children are drawing pictures in the classroom',
    'I usually drink water before I go for a walk',
    'Our new neighbor has a friendly dog named Milo',
    'The small bakery opens early and sells warm bread',
    'We watched a funny movie after dinner last night',
    'Put your keys on the shelf beside the front door',
    'The doctor said that regular sleep is important',
    'My phone battery is low, so I need a charger',
    'She bought a train ticket for the weekend trip',
    'The park is quiet when people leave their phones at home',
    'I write three useful words in my notebook each day',
    'Our teacher uses pictures to explain new ideas',
    'The waiter brought us two glasses of cold water',
    'He forgot his password but remembered the answer later',
    'A short walk can improve your mood',
    'The library has comfortable chairs near the window',
    'We should recycle paper and plastic whenever possible',
    'Her grandmother tells interesting stories about the village',
    'The morning train was crowded but arrived on time',
    'I keep a small plant beside my computer',
    'They are planning a picnic if the weather stays sunny',
    'The blue notebook contains all my travel plans',
  ],
  medium: [
    'The customer changed the delivery address before the order was shipped',
    'Our team meets every Friday to discuss progress and difficulties',
    'The hotel recommended a quieter restaurant outside the city center',
    'She chose a practical solution instead of waiting for perfect conditions',
    'The article explains how small habits influence long-term health',
    'Although the instructions were brief, everyone completed the task correctly',
    'The museum offers guided tours for visitors who want more context',
    'We postponed the meeting because several important documents were missing',
    'A reliable calendar helps me balance work, study, and personal time',
    'The engineer tested the device under several different conditions',
    'People often remember stories more easily than isolated facts',
    'The community created a garden where children could learn about nature',
    'He apologized for the confusion and suggested a clearer explanation',
    'The train was delayed, so we used the extra time to review our notes',
    'Good feedback should identify a problem without discouraging the learner',
    'The company reduced unnecessary packaging to lower its environmental impact',
    'She looked for a course that matched her schedule and learning goals',
    'The interview became more interesting when the guest described a personal challenge',
    'Before making a decision, compare the benefits with the possible risks',
    'The recipe can be adapted for people who avoid dairy products',
    'Our guide explained why the old bridge was important to the local community',
    'The software update improved performance but introduced a minor visual problem',
    'A respectful disagreement can lead to a better idea',
    'The students collected evidence before presenting their conclusions',
    'She has worked remotely since the office moved to another neighborhood',
  ],
  hard: [
    'The committee rejected the proposal because its long-term consequences had not been examined carefully',
    'While the initial results appeared promising, a larger study produced a more complicated picture',
    'A successful negotiation depends on understanding what the other side genuinely needs',
    'The researchers developed a framework that allows different communities to share reliable data',
    'Had the warning been taken seriously, the organization might have avoided the disruption',
    'The policy was revised after independent reviewers identified several unintended effects',
    'People are more likely to adopt sustainable habits when convenient alternatives are available',
    'The lecture examined how language can influence the way a society understands responsibility',
    'Although the evidence was incomplete, the investigators found enough information to continue',
    'The project succeeded because every participant understood both the objective and the limitations',
    'A persuasive argument should acknowledge reasonable objections before presenting its conclusion',
    'The company introduced a flexible schedule so employees could manage different responsibilities',
    'What distinguishes expert judgment is the ability to recognize uncertainty without becoming paralyzed',
    'The translation was accurate in meaning but failed to preserve the tone of the original speech',
    'Unless the data is interpreted within its context, the final comparison may be misleading',
    'The expedition revealed that the region was changing faster than previous surveys had suggested',
    'Effective leadership requires decisions that remain consistent even when circumstances become difficult',
    'The novel explores whether technological progress can exist without weakening human connection',
    'By examining several independent sources, the journalist avoided relying on a single unverified claim',
    'The new regulations are intended to protect consumers while allowing small businesses to remain competitive',
    'A solution that appears efficient today may create costs that are difficult to measure later',
    'The professor encouraged students to question assumptions rather than simply memorize conclusions',
    'The report provides a detailed account of how the crisis developed and why it lasted so long',
    'Despite considerable pressure, the team refused to publish results that had not been verified',
    'The quality of a decision depends not only on the available evidence but also on how it is evaluated',
  ],
};

// Shared sentence data is intentionally exported for the Vocabulary focus.
// eslint-disable-next-line react-refresh/only-export-components
export const VOCABULARY_SENTENCES: Record<'en-US', Record<Difficulty, string[]>> = {
  'en-US': vocabularySentences,
};

const SAMPLE_SENTENCES: Record<'en-US', Record<Difficulty, string[]>> = {
  'en-US': {
    easy: cleanSentences([
      'Practice makes perfect',
      'Keep going one step at a time',
      'Small steps make a big difference',
      'Every day is a fresh start',
      'Learning takes time and patience',
      'Believe in yourself',
      'Stay calm and focused',
      'Good things take time',
      'Dream big and work hard',
      'Enjoy the little moments',
      'Mia found a small garden behind the library',
      'She planted three seeds and watered them every morning',
      'The first green leaves appeared after a week',
      'Mia shared the fresh herbs with her neighbors',
      'Soon the little garden became a place for everyone',
      ...easyGenerated,
      ...easyAdditional,
      ...cambridgeGenerated.easy,
      ...grammarSentences.easy,
      ...vocabularySentences.easy,
      ...diverseSentenceBank.easy,
    ]),
    medium: cleanSentences([
      'Practice makes perfect when it comes to language learning',
      'Technology is best when it brings people together',
      'In the middle of difficulty lies opportunity',
      'Life is what happens when you are busy making other plans',
      'The best way to predict the future is to invent it',
      'It does not matter how slowly you go as long as you do not stop',
      'You miss one hundred percent of the shots you do not take',
      'The only way to do great work is to love what you do',
      'The journey of a thousand miles begins with one step',
      'Opportunities do not happen. You create them',
      'Alex started a new project with a simple plan',
      'Each morning, the team reviewed one small goal',
      'Their careful progress revealed problems early',
      'They adjusted the plan and learned from every setback',
      'After several weeks, the project was ready to share',
      ...mediumGenerated,
      ...mediumAdditional,
      ...cambridgeGenerated.medium,
      ...grammarSentences.medium,
      ...vocabularySentences.medium,
      ...diverseSentenceBank.medium,
    ]),
    hard: cleanSentences([
      'The only limit to our realization of tomorrow is our doubts of today',
      'Do not go where the path may lead, go instead where there is no path and leave a trail',
      'To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment',
      'I have not failed. I have just found ten thousand ways that will not work',
      'Whether you think you can or you think you cannot, you are right',
      'Success usually comes to those who are too busy to be looking for it',
      'Do not be afraid to give up the good to go for the great',
      'I find that the harder I work, the more luck I seem to have',
      'The future belongs to those who believe in the beauty of their dreams',
      'You cannot cross the sea merely by standing and staring at the water',
      'When the storm disrupted the expedition, the researchers protected their notes',
      'They then compared their observations with the forecasts prepared before departure',
      'Although the original route was no longer safe, their evidence suggested another path',
      'The team postponed the journey rather than allowing urgency to replace careful judgment',
      'Their patience ultimately produced a safer and more accurate account of the region',
      ...hardGenerated,
      ...hardAdditional,
      ...cambridgeGenerated.hard,
      ...grammarSentences.hard,
      ...vocabularySentences.hard,
      ...diverseSentenceBank.hard,
    ]),
  },
};

export default SAMPLE_SENTENCES;
