const SAMPLE_SENTENCES = {
  'en-US': [
    "Practice makes perfect when it comes to language learning",
    "Technology is best when it brings people together",
    "In the middle of difficulty lies opportunity",
    "Life is what happens when you're busy making other plans",
    "The only limit to our realization of tomorrow is our doubts of today",
    "Do not go where the path may lead, go instead where there is no path and leave a trail",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment",
    "I have not failed. I've just found 10,000 ways that won't work",
    "The best way to predict the future is to invent it",
    "It does not matter how slowly you go as long as you do not stop",
    "You miss 100% of the shots you don't take",
    "Whether you think you can or you think you can't, you're right",
    "The only way to do great work is to love what you do",
    "Don't watch the clock; do what it does. Keep going",
    "The journey of a thousand miles begins with one step",
    "Believe you can and you're halfway there",
    "The only thing we have to fear is fear itself",
    "Do what you can, with what you have, where you are",
    "Success usually comes to those who are too busy to be looking for it",
    "Don't be afraid to give up the good to go for the great",
    "I find that the harder I work, the more luck I seem to have",
    "The future belongs to those who believe in the beauty of their dreams",
    "It always seems impossible until it's done",
    "The best revenge is massive success",
    "The only place where success comes before work is in the dictionary",
    "Opportunities don't happen. You create them",
    "Don't let yesterday take up too much of today",
    "You can't cross the sea merely by standing and staring at the water",
  ],
};

export default SAMPLE_SENTENCES;
